apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    user: ask
    password: "ask"
    database: "ask"
    basicAuth: false
    isDefault: false
    readonly: false

