{
 "title": "Postgresql",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transactions",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Invoices table size",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "table_size",
     "select": [
      [
       { "params": [ "size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "schema", "operator": "=", "value": "public" },
      { "condition": "AND", "key": "table", "operator": "=", "value": "invoices" }
     ]
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Index scans",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "relation_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "indexes",
     "select": [
      [
       { "params": [ "idx_scan" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Tuples fetch",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "relation_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "indexes",
     "select": [
      [
       { "params": [ "idx_tup_fetch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Tuples read",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "relation_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "indexes",
     "select": [
      [
       { "params": [ "idx_tup_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slow queries time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "long_running_queries",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "long_running_queries",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "long_running_queries",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(\"duration_ms\", 10), \"query\" FROM \"long_running_queries\" \nWHERE $timeFilter \nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}